"""add published year to books

Revision ID: 1497c0959b0a
Revises: adf4f13714bd
Create Date: 2026-07-25 22:19:19.925903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1497c0959b0a'
down_revision: Union[str, Sequence[str], None] = 'adf4f13714bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('published_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'published_year')
    # ### end Alembic commands ###
